[server]
headless = true
port = 10000

[browser]
serverAddress = "0.0.0.0"
serverPort = 10000

[theme]
primaryColor="#353430"
backgroundColor="#eaf2f0"
secondaryBackgroundColor="#a5bda9"
textColor="#353c5e"
