[server]
headless = true
port = 10000

[browser]
serverAddress = "0.0.0.0"
serverPort = 10000

[theme]
primaryColor = "#2D2D2D"
backgroundColor = "#FAFAFA"
secondaryBackgroundColor = "#EAEAEA"
textColor = "#333333"
font = "sans serif"

